import { beforeEach, describe, expect, it, vi } from 'vitest'

import { useLocaleStore } from '../locale-store'
import { useProjectStore } from '../project-store'
import {
  useWorkflowStore,
  workflowResourceConflictMessage,
  type WorkflowDefinition,
} from '../workflow-store'

const projectPath = 'C:\\novels\\resource-conflict'
const projectSession = {
  projectId: 'resource-conflict',
  leaseId: 'lease-resource-conflict',
  projectPath,
}

function definition(
  title: string,
  resourceKeys: string[],
  execute: WorkflowDefinition['steps'][number]['executor'],
): WorkflowDefinition {
  return {
    type: 'chapter_creation',
    title,
    projectPath,
    projectSession,
    resourceKeys,
    steps: [{ name: title, description: title, executor: execute }],
  }
}

beforeEach(() => {
  useLocaleStore.setState({ locale: 'en-US' })
  useProjectStore.setState({
    currentProject: {
      id: projectSession.projectId,
      sessionLease: projectSession.leaseId,
      name: 'Resource conflict',
      path: projectPath,
      novelConfig: {},
    } as never,
  })
  useWorkflowStore.setState({
    activeRuns: [],
    history: [],
    globalLogs: [],
    waitingRuns: {},
    currentRun: null,
    waitingForConfirm: false,
    waitingAfterStepIndex: -1,
  })
})

describe('workflow logical resource single-flight', () => {
  it('provides the conflict explanation in both interface languages', () => {
    expect(workflowResourceConflictMessage('zh-CN', '第 1 章')).toBe(
      '该项目的相同内容正在由「第 1 章」生成。请等待完成或取消任务后再试。',
    )
    expect(workflowResourceConflictMessage('en-US', 'Chapter 1')).toBe(
      'The same project content is already being generated by "Chapter 1". Wait for it to finish or cancel it before retrying.',
    )
  })

  it('rejects a duplicate resource in the same project while preserving the first run', async () => {
    let releaseFirst!: () => void
    const firstExecutor = vi.fn(() => new Promise<void>((resolve) => { releaseFirst = resolve }))
    const duplicateExecutor = vi.fn().mockResolvedValue(undefined)

    const firstCompletion = useWorkflowStore.getState().startWorkflow(
      definition('Chapter 1 first', ['chapter:1'], firstExecutor),
    )
    await vi.waitFor(() => expect(firstExecutor).toHaveBeenCalledOnce())

    const duplicate = definition('Chapter 1 duplicate', ['chapter:1'], duplicateExecutor)
    expect(useWorkflowStore.getState().getResourceConflict(duplicate)).toMatchObject({
      title: 'Chapter 1 first',
    })
    await useWorkflowStore.getState().startWorkflow(duplicate)

    expect(duplicateExecutor).not.toHaveBeenCalled()
    expect(useWorkflowStore.getState().history[0]).toMatchObject({
      title: 'Chapter 1 duplicate',
      status: 'failed',
      error: 'The same project content is already being generated by "Chapter 1 first". Wait for it to finish or cancel it before retrying.',
    })

    releaseFirst()
    await firstCompletion
  })

  it('allows different chapter resources in the same project to run concurrently', async () => {
    let releaseFirst!: () => void
    let releaseSecond!: () => void
    const firstExecutor = vi.fn(() => new Promise<void>((resolve) => { releaseFirst = resolve }))
    const secondExecutor = vi.fn(() => new Promise<void>((resolve) => { releaseSecond = resolve }))

    const firstCompletion = useWorkflowStore.getState().startWorkflow(
      definition('Chapter 1', ['chapter:1'], firstExecutor),
    )
    const secondDefinition = definition('Chapter 2', ['chapter:2'], secondExecutor)
    await vi.waitFor(() => expect(firstExecutor).toHaveBeenCalledOnce())

    expect(useWorkflowStore.getState().getResourceConflict(secondDefinition)).toBeNull()
    const secondCompletion = useWorkflowStore.getState().startWorkflow(secondDefinition)
    await vi.waitFor(() => expect(secondExecutor).toHaveBeenCalledOnce())
    expect(useWorkflowStore.getState().activeRuns).toHaveLength(2)

    releaseFirst()
    releaseSecond()
    await Promise.all([firstCompletion, secondCompletion])
  })
})
