import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('v0.8.1 release metadata', () => {
  it('uses the release version in package metadata', () => {
    const pkg = JSON.parse(readFileSync('package.json', 'utf8')) as { version: string }
    expect(pkg.version).toBe('0.8.1')
  })

  it('keeps the bilingual v0.8.1 three-issue release scope, five-asset contract, and platform limitations in the READMEs', () => {
    const chineseReadme = readFileSync('README.md', 'utf8')
    const englishReadme = readFileSync('README_en.md', 'utf8')

    expect(chineseReadme).toContain('v0.8.1')
    expect(chineseReadme).toContain('重大更新')
    expect(chineseReadme).toContain('#78')
    expect(chineseReadme).toContain('用户配置温度')
    expect(chineseReadme).toContain('Kimi')
    expect(chineseReadme).toContain('#84')
    expect(chineseReadme).toContain('旧角色')
    expect(chineseReadme).toContain('侧边栏')
    expect(chineseReadme).toContain('#85')
    expect(chineseReadme).toContain('有界续写')
    expect(chineseReadme).toContain('不完整')
    expect(chineseReadme).toContain('不落盘')
    expect(chineseReadme).toContain('五项资产')
    expect(chineseReadme).toContain('ai-novel-writer-setup-0.8.1.exe')
    expect(chineseReadme).toContain('ai-novel-writer-setup-0.8.1.exe.blockmap')
    expect(chineseReadme).toContain('latest.yml')
    expect(chineseReadme).toContain('ai-novel-writer-mac-arm64-0.8.1-installer.dmg')
    expect(chineseReadme).toContain('ai-novel-writer-mac-arm64-0.8.1-installer.dmg.sha256')
    expect(chineseReadme).toContain('Windows x64')
    expect(chineseReadme).toContain('Windows 安装包未签名')
    expect(chineseReadme).toContain('应用内更新')
    expect(chineseReadme).toContain('未签名、未公证')
    expect(chineseReadme).toContain('macOS ARM64')
    expect(chineseReadme).toContain('手动更新')

    expect(englishReadme).toContain('v0.8.1')
    expect(englishReadme).toContain('major update')
    expect(englishReadme).toContain('#78')
    expect(englishReadme).toContain('user-configured temperature')
    expect(englishReadme).toContain('Kimi')
    expect(englishReadme).toContain('#84')
    expect(englishReadme).toContain('legacy character')
    expect(englishReadme).toContain('sidebar')
    expect(englishReadme).toContain('#85')
    expect(englishReadme).toContain('bounded continuation')
    expect(englishReadme).toContain('incomplete')
    expect(englishReadme).toContain('not persisted')
    expect(englishReadme).toContain('five assets')
    expect(englishReadme).toContain('ai-novel-writer-setup-0.8.1.exe')
    expect(englishReadme).toContain('ai-novel-writer-setup-0.8.1.exe.blockmap')
    expect(englishReadme).toContain('latest.yml')
    expect(englishReadme).toContain('ai-novel-writer-mac-arm64-0.8.1-installer.dmg')
    expect(englishReadme).toContain('ai-novel-writer-mac-arm64-0.8.1-installer.dmg.sha256')
    expect(englishReadme).toContain('Windows x64')
    expect(englishReadme).toContain('Windows installer is not code-signed')
    expect(englishReadme).toContain('in-app update')
    expect(englishReadme).toContain('unsigned and not notarized')
    expect(englishReadme).toContain('macOS ARM64')
    expect(englishReadme).toContain('manual update')
  })

  it('keeps stale Mythpen branding out of release metadata', () => {
    const releaseConfig = readFileSync('package.json', 'utf8')
    expect(releaseConfig.toLowerCase()).not.toContain('mythpen')
  })

  it('lets the Windows smoke command discover the current release executable', () => {
    const smokeScript = readFileSync('scripts/smoke-win-app.ps1', 'utf8')
    expect(smokeScript).toContain('package.json')
    expect(smokeScript).toContain('AI小说作家.exe')
  })
})
